### ISSUE TITLE
when i try fake player name i get " ????????????????? "

### ISSUE THREAD

**Issue by AbdulazizQQ** [Bluscream/Name-Faker-TS3-Plugin#1]
like this

https://gyazo.com/9bccd5ec2848b65a2d99c0d98abd52f4

**Comment by Bluscream** [comment]
As you see [here](https://github.com/Bluscream/Name-Faker-TS3-Plugin/blob/master/plugin.cpp#L372) i didn't finaly managed it to implement that functionality. If you have a idea how to do it, please open up a pull request [here](https://github.com/Bluscream/Name-Faker-TS3-Plugin/pulls).
